#This is Jose Mata's submission for COMP 540 - Automata's CFG Project. Fall 2024, Bridgewater State University

import random

#Create the data structure - a dictionary of lists - for the grammar in the CFG Project Instructions
grammar1 = {
    'S' : ['AB', 'aS'],
    'A' : ['aA', 'b'], 
    'B' : ['bB', 'a']
    }

start_symbol = 'S'

def generate_random_string(word, variable):
    list_of_sets = grammar1[variable]
    chosen_set = list_of_sets[random.randint(0,len(list_of_sets)-1)]
    #print(chosen_set+'\n')
    for char in chosen_set:
        if char.isupper():
            word = generate_random_string(word, char)
        else:
            word = word + char
    if word.islower():
        return word


while True: 
    answer = input("This is Jose Mata's CFG Project. Please enter:\n'1' to produce a random string from the CFG shown in the assignment instructions.\n'2' to display the production rules of this grammar.\n'3' to exit the pogram.\n")
    if answer == '1':
        empty_word = ''
        random_word = generate_random_string(empty_word, start_symbol)
        print("The random word generated by this grammar is: " + random_word + "\n")
    elif answer == '2':
        print("The following are the production rules of this grammar:")
        for key, value in grammar1.items():
            print(key + ' : ' + str(value))
        print("Start symbol: " + start_symbol + "\n")
    elif answer == '3':
        print("Exiting the program...\n")
        break
    else:
        print("Answer is invalid.\n")
