#This is Jose Mata's submission for COMP 540 - Automata's CFG Project. Fall 2024, Bridgewater State University

import random

#Create the data structure - a dictionary of lists - for the grammar in the CFG Project Instructions
grammar1 = {
    'S' : ['AB', 'aS'],
    'A' : ['aA', 'b'], 
    'B' : ['bB', 'a']
    }


def generate_random_string(word, variable):
    list_of_sets = grammar1[variable]
    chosen_set = list_of_sets[random.randint(0,1)]
    print(chosen_set+'\n')
    for char in chosen_set:
        if char.isupper():
            word = generate_random_string(word, char)
        else:
            word = word + char
    if word.islower():
        return word


while True: 
    answer = input("Please enter '1' to produce a random string from the CFG shown in the assignment instructions, '2' to display the production rules of this grammar, or '3' to exit the pogram.\n")
    if answer == '1':
        print("The following is a random string produced by the CFG Grammar: \n")
        empty_word = ''
        random_word = generate_random_string(empty_word, 'S')
        print("The random word generated by this grammar is: " + random_word + "\n")
    elif answer == '2':
        print("The following are the production rules of this grammar:\nS:AB\nS:aS\nA:aA\nA:b\nB:bB\nB:a\nStart symbol: S\n\n")
    elif answer == '3':
        print("Exiting the program...\n")
        break
    else:
        print("Answer is invalid.\n")
